### PR TITLE
V1.4.2

### PR DESCRIPTION
**Pull request by jeremygurr**

### CODE REVIEW

**Comment by yrmvgh** [comment]
Oh, maybe this fixes my 350 spellpower halfling - is this deployed or is this upcoming?

**Comment by jeremygurr** [comment]
it's deployed but I doubt it would do much for your spell power. That part caused very little difference. 

I'm not sure where the 350 spell power comes from. Create an issue for that and I'll look into it. I expect over extended games players might be able to get in the 300s, but I'm guessing that's not the case here?

**Comment by yrmvgh** [comment]
> not sure where the 350 spell power

I think it's because wild magic, archmage, and power are all multiplicative - and seemingly, one or more of them is flagged to allow your spells to break even the looser 200 spower cap?

**Comment by jeremygurr** [comment]
That makes sense if you've got 3 enhancers. Probably should tweak the stepdown a little though.

**Comment by yrmvgh** [comment]
Might want to make the cap absolute as well? Having over 200 spower is pretty nuts. Especially on Lair 1, one-shotting most enemies with magic dart :grinning:

**Pull request merged**
