### PR TITLE
Reform 1: remove "conjurations" from several spells

### PR DESCRIPTION
**Pull request by yrmvgh**
Also, adding blinkbolt. A player-castable blinkbolt with significantly more strict parameters than Raiju blinkbolt, so that it can't replace Cblink. Should be tons of fun for players, based on how beloved Lightning Leap is in Te4.

### CODE REVIEW

**Comment by yrmvgh** [comment]
Please feel free to edit or revert my changes, or add more of your own. This isn't my pet project, it's a revolution! Let's make spells great again!

**Comment by yrmvgh** [comment]
long ago I mentioned that reviving Detect Items would be super good for pacifist or simple_depth players - they mostly want to grab the items and go, not stay and fight. When you're not a serial slayer & floor clearer, it's hard to know that you've grabbed all the available loot - enter Detect Items! Probably put it in Charms, these days. Mayyybe charms/tloc? It could have an earth flavor... "feel" the items through the ground.

Anyway, the effect still can be found in the Dowsing card, but I'm not sure how to call it from a spell:
https://github.com/jeremygurr/dcssca/blob/d027b6c671200bb74a8d5b4f1528e6390464c3d5/crawl-ref/source/decks.cc#L2188

**Comment by yrmvgh** [comment]
We could bring stoneskin back, but if we do, it might should also be packaged with a switch to the "always on" paradigm. Also @G0rg0 mentioned [disjunction](http://crawl.chaosforge.org/Disjunction), but said it used to be OP, so we'd need to tone it down.

**Comment by jeremygurr** [comment]
yeah stoneskin should definitely be back. blinkbolt seems interesting.

**Comment by yrmvgh** [comment]
I cannot believe that travis allowed me to edit an enum. I'm really expecting this to explode when compiled...

**Comment by yrmvgh** [comment]
Blinkbolt is probably just a damage spell at this point.
This file probably needs to mention blinkbolt?
https://github.com/jeremygurr/dcssca/blob/DCSS-CA-Spellbook-Reform/crawl-ref/source/spl-transloc.h

**Comment by yrmvgh** [comment]
wow

14<Sequell> 200 power[1/1]: With all skills at 27, you need 3 enhancers and 33 INT, or 2 enhancers and 50 INT, or 1 enhancer and 75 INT, or no enhancers and 112 INT. Four enhancers don't give an effect better than three, but three enhancers plus Wild Magic or Augmentation do.

**Comment by jeremygurr** [comment]
changes to enums need to be made at the end, or they break saved games. 

Also, there are other problems here that break things, but it would take me more time to go through and fix these things than it would for me to just implement the feature myself. In other words, you are ready to take the next step in improving your development skills. I need you to compile the code and run it locally so you can test it and make sure your changes work before making a pull request. Otherwise, like I said, I spend more time working with you to troubleshoot issues than it would take for me to just do it myself. 

Just use this command in your terminal in the source folder of the project:

make NOASSERTS=True TILES=t debug-lite 

then just execute the crawl binary and you can try out your changes. Once you have proven they work properly, you can commit and push those changes into this pull request, and I can move ahead confidently with merging it.

**Comment by yrmvgh** [comment]
Exciting and scary, okay! Should I wait for 1.5 or get started on this now?

**Comment by jeremygurr** [comment]
you can get started, should not be much in the way of conflicts.

**Comment by jeremygurr** [comment]
You need to split off the blinkbolt stuff from the conjuration removal. I might allow the blinkbolt in if you can get it working, at least to experiment with, but I'm not real keen on the conjuration changes, so as it stands, those can keep this pull request from moving forward.

**Comment by yrmvgh** [comment]
Ok, this PR was super-back-burnered for me anyways, because it's pretty difficult, but yeah, I will split this when I next noodle with it. And I'll aim to make smaller PRs in general so that they can be cherry picked.

**Comment by yrmvgh** [comment]
I think I've got everything I need from this moved into blinkbolt-testing

**Pull request closed without merging**
