### PR TITLE
some readme updates

### PR DESCRIPTION
**Pull request by yrmvgh**

### CODE REVIEW

**Comment by yrmvgh** [comment]
Don't be angry, but I'm going to push this big green button just to see if it actually works.

**Comment by yrmvgh** [comment]
Ok, it works... is that ok for me to do with readme / other documentation updates only?

**Comment by jeremygurr** [comment]
It's better for me to check over each pull request so I can keep up with everything and make sure things are aligning with where I want to go.

**Comment by jeremygurr** [comment]
I'm trying to get these permissions set right, but don't know exactly what I'm doing, so tell me if it prevents you from doing something that you should be able to do.

**Pull request merged**
