### PR TITLE
food shops out

### PR DESCRIPTION
**Pull request by yrmvgh**
food shops out

### CODE REVIEW

**Comment by yrmvgh** [comment]
I'm gonna try to keep uddating this patch despite github making that a real pain in the ass, so don't merge yet

**Comment by yrmvgh** [comment]
Ok it's mergable now

**Comment by yrmvgh** [comment]
On second thought, it occurs to me that "random shop" can still spawn food shops. Is this undesirable? I thiiiiink it is. Correcting that behavior might be beyond my abilities, but I'm looking at it now.

All FIXED food shops are gone now, including "food shop / distillery" type things.

But "random shop" will stilll occasionally be food, albeit rarely.

**Comment by jeremygurr** [comment]
I think that's fine. We want rare food shops for now at least.

**Pull request merged**
