### PR TITLE
Display damage for acid

### PR DESCRIPTION
**Pull request by Sandman25DCSS**
Display damage for acid

### CODE REVIEW

**Comment by Sandman25DCSS** [comment]
Oops, there is a compile error. I'll try to fix it

**Comment by jeremygurr** [comment]
If you can update this branch from master, it should take care of the travis issue

**Comment by Sandman25DCSS** [comment]
Merge didn't help :(

**Comment by jeremygurr** [comment]
Ok merge once more and it should be ok

**Pull request merged**
