### PR TITLE
this'll almost certainly fix DEAD MONSTER message bug

### PR DESCRIPTION
**Pull request by yrmvgh**
because the nice folks in ##crawl-dev corrected the bad solution I initially came up with!

### CODE REVIEW

**Comment by jeremygurr** [comment]
That's exactly the same as before. It is the same code, just moved around. Won't make any difference, unless I'm missing something here.

**Comment by yrmvgh** [comment]
It saves a string before the monster is "hurted", so that it can refer to the previously-alive monster instead of DEAD MONSTER

**Comment by yrmvgh** [comment]
It's possible that line 947 (in my version) could/should be moved even earlier to super-ensure the monster doesn't die before the string gets saved

**Comment by yrmvgh** [comment]
According to |amethyst, however, it simply needs to happen before mons->hurt does

**Comment by yrmvgh** [comment]
https://github.com/jeremygurr/dcssca/blob/0f8b4f76d0d1ccc73b291e3f5593975705818f57/crawl-ref/source/art-func.h#L736 has a similar thing going on

**Comment by jeremygurr** [comment]
Oh I get it. You are right, the name does change after the hurt call, so this should work.

**Pull request merged**
