### PR TITLE
might make rTrample work, but isn't rTrample bad?

### PR DESCRIPTION
**Pull request by yrmvgh**

### CODE REVIEW

**Comment by yrmvgh** [comment]
might be more of a Good mut if it also knocked off a point or two of damage from trample flavored attacks. Just a little, to ensure there's an upside, albeit an upside that's both small and narrow.

It's good to have some weird or non-amazing muts in the goodmut pool, but usually I _want_ to be knocked away from the other monsters, it's free repositioning in a fork where repositioning is difficult

**Comment by jeremygurr** [comment]
Hmm, I'd rather the flavor be fairly pure. But maybe you're right about it not being clearly a good thing, so we can mark it as depends so you don't get if from bene mut.

**Comment by yrmvgh** [comment]
Hmm. I'd prefer for it to stick around and continue cluttering up the "good" pool, but it's not "good" as it stands. Any other ideas on making it beneficial?

I guess to keep the Good mut pool from being TOO good, we can simply increase the weight of other "meh" good-muts whenever we move one into depends-muts.

**Comment by yrmvgh** [comment]
Haha, crazy idea... we could replace it with a Good mut that causes you to take a free step back (a forced Trample as it were) whenever you take 30% damage from a melee attack. Probably would be more-good-than-bad (but sometimes annoying) on sword, mace, etc, but would be annoying as hell on Axe. So incredibly annoying.

**Comment by yrmvgh** [comment]
Actually, that's not as crazy as I thought... if it's not forced. when damaged 30% or more by a melee attack, for one turn your movement delay is halved (to 5.5 for most characters, but 1.2 or so with Chei)

**Pull request merged**
