### PR TITLE
big monsters smash doors

### PR DESCRIPTION
**Pull request by yrmvgh**

### CODE REVIEW

**Comment by jeremygurr** [comment]
Some of these are not big monsters that should logically be able to smash doors (moth?), and several have above animal intelligence, so they can just open doors. I'm okay with adding this to a few monsters where it really makes sense, but overdoing this removes an important strategic option from the player.

**Comment by yrmvgh** [comment]
Yeah, the moth is just so angry I was thinking it WILLS the door out of existence, heh. I'll tone it down. The editor's sharpie is a very powerful temptation, easy to go wild with.

Changing CAN OPEN to SMASH DOOR on some of those monsters is intentional as a "siege breaking" sort of thing that a brute would do, but I understand if that's too much unnecessary change. Would you like me to restore OPEN, and only OPEN, to every monster that I switched from opening to smashing?

**Comment by jeremygurr** [comment]
I think that open doors flag is obsolete. I think any creature with human intelligence can open doors. Although I could be wrong.

The key here is we don't want a cool effect too common, or it loses it's coolness. For a dragon, that makes sense. A door should not even slow them down. But even for a bear, where maybe logically they could smash a door, it just becomes too much. I think it should be reserved for the creatures that would beyond question smash a door to pieces given a chance.

**Comment by yrmvgh** [comment]
Got it!

**Comment by yrmvgh** [comment]
I think black bears are more of a "maybe" or "it might take them awhile". Polar bears though? Can we keep polar bears? A door is like a rice paper screen to them. :grin: 

On a more shaky justification... apocalypse crab? It says apocalypse on it. Surely a door can't hold back an apocalypse!

**Comment by Sandman25DCSS** [comment]
I have two comments:
1) Does Vault Warden's seal doors ability work with smashed doors? If not, then we can actually make player's life easier in Vaults.
2) If answer to first question is true, how about destroying a door when it is opened by monster? My intention is too fix "door-dancing" when you close the door every turn, monster opens the door every turn and you restore HP/MP/SP in the process.

**Pull request merged**
